-- ============================================================
-- LOANVAULT DATABASE MIGRATION & SCHEMA INITIALIZATION
-- Executed on Spring Boot startup to ensure columns exist in Neon DB
-- ============================================================

-- Ensure active and on_leave status columns exist on the users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS on_leave BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS servicing_branch_id BIGINT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS branch VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS date_of_birth VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS pan_number VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS aadhaar_number VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS address_line1 VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS city VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS state VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS pincode VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS employment_type VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS employer_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS monthly_income NUMERIC(12,2);
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_completed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS kyc_verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP;
